### ISSUE TITLE
Add support for a hand of cards

### ISSUE THREAD

**Issue by bstee615** [5mindung/core#5]
In the real game, the user will have a hand of cards they can play from. This gives us two **domain rules**:

1. [x] They can only play cards that are in their hand.
2. [x] After they play a card, it will disappear from their hand.

I'd suggest implementing 1. then 2. afterwards. This is called **iterative development**: finish an easier version of the feature in a short amount of time and improve on it bit-by-bit.

Tips:
- You can use a `list` to hold the hand of cards. You have to assign it to a variable. Make a list like this:
`cards = ['bow', 'shield']`

- To check if an item is in a list, use `<item> in <list>`. You'll have that in an `if` statement. So, in this example:
```
if 'bow' in list:
  # Do something
```

- To remove a card, call `list.remove(<item>)`. So, in this example:
```
>>> cards = ['bow', 'shield']
>>> cards.remove('bow')
>>> cards
['shield'] # Now has shield removed
```

**Comment by atsickels** [comment]
Currently the card is removed from the players hand, but will need to be moved to the hero class to handle the removal properly, like it is in the enemy class. Temporarily fixed the issue, but leaving unchecked until properly implemented.
